// Machine-generated Arabic draft for role guides. Editorial status: draft_machine_generated / review_required.
export const ROLE_GUIDE_ARABIC_DRAFT: Record<string, string> = {
  "Super Admin": "مسؤول النظام",
  "Full system administrator": "إدارة شاملة للنظام",
  "Super Admins have unrestricted access to the entire CAFA PMIS. They are responsible for user management, system configuration, and data integrity oversight.": "يتمتع مسؤولو النظام بوصول غير مقيد إلى كامل نظام CAFA PMIS. وهم مسؤولون عن إدارة المستخدمين، وتهيئة النظام، والإشراف على سلامة البيانات.",
  "All modules and data across all states and sectors": "جميع الوحدات والبيانات عبر كافة الولايات والقطاعات",
  "User management (create, edit, suspend, deactivate)": "إدارة المستخدمين (إنشاء، تعديل، تعليق، إلغاء التفعيل)",
  "Audit log — full history of all system actions": "سجل التدقيق — سجل كامل لجميع إجراءات النظام",
  "System Manual editing and chapter management": "تحرير دليل النظام وإدارة الفصول",
  "AI settings and usage logs": "إعدادات الذكاء الاصطناعي وسجلات الاستخدام",
  "All project, report, plan, and risk records": "جميع سجلات المشاريع، والتقارير، والخطط، والمخاطر",
  "Users and invitations": "المستخدمون والدعوات",
  "Projects (all states and sectors)": "المشاريع (كافة الولايات والقطاعات)",
  "Reports of all types": "جميع أنواع التقارير",
  "Plans of all types": "جميع أنواع الخطط",
  "Risks": "المخاطر",
  "Manual chapters and sections": "فصول وأقسام الدليل",
  "Projects at any stage": "المشاريع في أي مرحلة",
  "Reports at any stage": "التقارير في أي مرحلة",
  "Plans at any stage": "الخطط في أي مرحلة",
  "Project Reports": "تقارير المشاريع",
  "HQ Sector Reports": "تقارير قطاع المقر الرئيسي",
  "State Programme Reports": "تقارير برامج الولايات",
  "Custom dashboard exports": "تصدير لوحة التحكم المخصصة",
  "Full strategic dashboard with all KPI cards, all charts, all states, Donor Portfolio view, and Pending Approvals panel.": "لوحة تحكم استراتيجية شاملة تحتوي على جميع بطاقات مؤشرات الأداء الرئيسية، وكافة المخططات البيانية، وجميع الولايات، وعرض محفظة المانحين، ولوحة الموافقات المعلقة.",
  "All approval requests and decisions": "جميع طلبات وقرارات الموافقة",
  "Critical and high-level risks": "المخاطر الحرجة وعالية المستوى",
  "Assignments": "المهام المسندة",
  "@Mentions": "الإشارات (@Mentions)",
  "Due date reminders": "تذكيرات المواعيد النهائية",
  "System events and security alerts": "أحداث النظام وتنبيهات الأمان",
  "Always use the Audit Log to investigate unexpected data changes.": "استخدم دائماً سجل التدقيق للتحقيق في أي تغييرات غير متوقعة في البيانات.",
  "Avoid using the Super Admin account for daily operations — create a personal account with the appropriate role.": "تجنب استخدام حساب مسؤول النظام (Super Admin) للعمليات اليومية — قم بإنشاء حساب شخصي بالدور المناسب.",
  "Run the seed script after a fresh deployment to restore demo users.": "قم بتشغيل نص التغذية البرمجي (seed script) بعد تثبيت النظام الجديد لاستعادة مستخدمي العرض التجريبي.",
  "Executive Director": "المدير التنفيذي",
  "Strategic oversight — read-only": "إشراف استراتيجي — للعرض فقط",
  "The Executive Director has read-only access to all programme data for senior oversight. They cannot create or approve records, but receive escalated risk notifications.": "يتمتع المدير التنفيذي بصلاحية العرض فقط لجميع بيانات البرنامج لأغراض الإشراف الإداري. لا يمكن للمدير التنفيذي إنشاء أو اعتماد السجلات، ولكنه يتلقى إشعارات تصعيد المخاطر.",
  "All projects (read-only)": "جميع المشاريع (للعرض فقط)",
  "All reports (read-only)": "جميع التقارير (للعرض فقط)",
  "All plans (read-only)": "جميع الخطط (للعرض فقط)",
  "Dashboard — full strategic view": "لوحة التحكم — عرض استراتيجي شامل",
  "Risk register (read-only)": "سجل المخاطر (للعرض فقط)",
  "State and sector performance data": "بيانات أداء الولايات والقطاعات",
  "View all report types (read-only)": "عرض جميع أنواع التقارير (للعرض فقط)",
  "Dashboard exports": "تصدير لوحة التحكم",
  "Full strategic dashboard — same as Programme Manager. All KPI cards, all charts, Donor Portfolio, and State Performance table.": "لوحة تحكم استراتيجية شاملة — مماثلة للوحة تحكم مدير البرامج. تتضمن كافة بطاقات مؤشرات الأداء الرئيسية، وكافة المخططات البيانية، ومحفظة المانحين، وجدول أداء الولايات.",
  "Critical risk escalations (mandatory)": "تصعيد المخاطر الحرجة (إلزامي)",
  "High-level risk escalations": "تصعيد المخاطر عالية المستوى",
  "Major approval milestones": "المراحل الرئيسية للموافقات",
  "Use the Dashboard for daily programme overview.": "استخدم لوحة التحكم للاطلاع اليومي على سير البرنامج.",
  "The Beneficiary Breakdown modal (click Total Beneficiaries on dashboard) provides disaggregated data.": "نافذة تفصيل المستفيدين المنبثقة (انقر على إجمالي المستفيدين في لوحة التحكم) توفر بيانات مصنفة.",
  "For detailed project data, navigate to Projects and use the search and filter options.": "للحصول على بيانات تفصيلية عن المشاريع، انتقل إلى قسم المشاريع واستخدم خيارات البحث والتصفية.",
  "Cannot create, edit, or delete any records": "لا يمكن إنشاء أو تعديل أو حذف أي سجلات",
  "Cannot approve or reject projects, reports, or plans": "لا يمكن اعتماد أو رفض المشاريع أو التقارير أو الخطط",
  "Cannot manage users": "لا يمكن إدارة المستخدمين",
  "Programme Manager": "مدير البرامج",
  "Final approvals and programme oversight": "اعتمادات نهائية وإشراف برامجي",
  "Programme Managers give final approval for projects, reports, and plans. They also activate approved projects and plans, and manage the user directory.": "يقوم مديرو البرامج بمنح الموافقة النهائية على المشاريع والتقارير والخطط. كما يقومون بتفعيل المشاريع والخطط المعتمدة، وإدارة دليل المستخدمين.",
  "All projects across all states and sectors": "جميع المشاريع عبر كافة الولايات والقطاعات",
  "All reports across all states and sectors": "جميع التقارير عبر كافة الولايات والقطاعات",
  "All plans": "جميع الخطط",
  "User directory (read and limited admin)": "دليل المستخدمين (للقراءة وصلاحيات إدارية محدودة)",
  "Risk register across all sectors": "سجل المخاطر عبر جميع القطاعات",
  "Budget and donor portfolio data": "بيانات الميزانية ومحفظة المانحين",
  "Projects": "المشاريع",
  "Reports": "التقارير",
  "Plans": "الخطط",
  "Manual chapters and SOPs": "فصول الدليل وإجراءات العمل القياسية (SOPs)",
  "Projects — final approval (4th stage)": "المشاريع — الموافقة النهائية (المرحلة الرابعة)",
  "Plans — final approval and activation": "الخطط — الموافقة النهائية والتفعيل",
  "Reports — final approval (3rd stage)": "التقارير — الموافقة النهائية (المرحلة الثالثة)",
  "Project activation (Approved → Active)": "تفعيل المشروع (معتمد → نشط)",
  "Project closure": "إغلاق المشروع",
  "Full strategic dashboard. All KPI cards, all charts, Budget & Beneficiary snapshot strip, Pending Approvals panel, State Performance table.": "لوحة تحكم استراتيجية شاملة. تتضمن كافة بطاقات مؤشرات الأداء الرئيسية، وكافة المخططات البيانية، وشريط ملخص الميزانية والمستفيدين، ولوحة الموافقات المعلقة، وجدول أداء الولايات.",
  "All approval requests at Programme Manager stage": "جميع طلبات الموافقة في مرحلة مدير البرامج",
  "Overdue approvals": "الموافقات المتأخرة",
  "Check the Pending Approvals panel on the Dashboard daily.": "تحقق من لوحة الموافقات المعلقة في لوحة التحكم يومياً.",
  "Use Required Correction comments to flag data issues without rejecting a submission outright.": "استخدم تعليقات \"التصحيح المطلوب\" للإشارة إلى مشاكل البيانات دون رفض الطلب بشكل مباشر.",
  "Activate approved projects promptly — state officers cannot begin implementation until a project is Active.": "قم بتفعيل المشاريع المعتمدة فوراً — لا يمكن لمسؤولي الولايات البدء في التنفيذ حتى يصبح المشروع نشطاً.",
  "Senior Programme Coordinator": "منسق البرامج الأول",
  "Coordination review — multi-state programmes": "مراجعة تنسيقية للبرامج متعددة الولايات",
  "Senior Programme Coordinators perform coordination reviews — the 3rd stage of the approval chain for projects, reports, and plans. They coordinate cross-state and cross-sector activities.": "يقوم منسقو البرامج الأولون بإجراء مراجعات تنسيقية — وهي المرحلة الثالثة من سلسلة الموافقة على المشاريع والتقارير والخطط. وهم ينسقون الأنشطة العابرة للولايات والقطاعات.",
  "All projects (view and coordination review)": "جميع المشاريع (عرض ومراجعة تنسيقية)",
  "All reports (view and coordination review)": "جميع التقارير (عرض ومراجعة تنسيقية)",
  "All plans (view and coordination review)": "جميع الخطط (عرض ومراجعة تنسيقية)",
  "Risk register": "سجل المخاطر",
  "System Manual (content editing)": "دليل النظام (تحرير المحتوى)",
  "Manual section content edits": "تعديلات محتوى أقسام الدليل",
  "Projects — coordination approval (3rd stage)": "المشاريع — موافقة التنسيق (المرحلة الثالثة)",
  "Plans — coordination approval": "الخطط — موافقة التنسيق",
  "Reports — coordination approval (2nd stage)": "التقارير — موافقة التنسيق (المرحلة الثانية)",
  "Operational dashboard — project counts, beneficiaries, budget, approval queue, Reporting Analytics strip.": "لوحة تحكم تشغيلية — أعداد المشاريع، والمستفيدون، والميزانية، وطابور الموافقات، وشريط تحليلات التقارير.",
  "Coordination review requests": "طلبات المراجعة التنسيقية",
  "Project and report transitions": "انتقالات مراحل المشاريع والتقارير",
  "@Mentions and comments": "الإشارات (@Mentions) والتعليقات",
  "Use the Comments panel to provide structured feedback to submitters before advancing to the next stage.": "استخدم لوحة التعليقات لتقديم ملاحظات منظمة لمقدمي الطلبات قبل الانتقال إلى المرحلة التالية.",
  "For complex multi-state projects, check all state localities are correctly assigned before coordinating.": "بالنسبة للمشاريع المعقدة متعددة الولايات، تأكد من تعيين جميع مناطق الولايات بشكل صحيح قبل التنسيق.",
  "Technical Coordinator": "المنسق التقني",
  "Sector-restricted technical review": "مراجعة تقنية ضمن القطاع المكلّف",
  "Technical Coordinators review projects, plans, and reports within their assigned programme sector(s). All data access is automatically restricted to their sector. A TC with no sector assigned is effectively locked out.": "يقوم المنسقون التقنيون بمراجعة المشاريع والخطط والتقارير ضمن قطاع (قطاعات) البرنامج الموكلة إليهم. يتم تقييد الوصول إلى كافة البيانات تلقائياً بقطاعهم. المنسق التقني الذي ليس لديه قطاع موكل إليه لا يمكنه الوصول للنظام فعلياً.",
  "Projects in assigned sector(s) only": "المشاريع في القطاع (القطاعات) الموكل فقط",
  "Reports for assigned sector(s) only": "التقارير للقطاع (القطاعات) الموكل فقط",
  "Plans for assigned sector(s) only": "الخطط للقطاع (القطاعات) الموكل فقط",
  "Risk register (sector-restricted)": "سجل المخاطر (مقيّد بالقطاع)",
  "Risks with no project link — excluded": "المخاطر غير المرتبطة بمشروع — مستبعدة",
  "Projects (within assigned sector)": "المشاريع (ضمن القطاع الموكل)",
  "Reports (within assigned sector)": "التقارير (ضمن القطاع الموكل)",
  "Plans (within assigned sector)": "الخطط (ضمن القطاع الموكل)",
  "Risks (for sector-linked projects)": "المخاطر (للمشاريع المرتبطة بالقطاع)",
  "Projects — technical approval (2nd stage)": "المشاريع — الموافقة التقنية (المرحلة الثانية)",
  "Plans — technical approval": "الخطط — الموافقة التقنية",
  "Project Reports (sector-restricted)": "تقارير المشاريع (مقيّدة بالقطاع)",
  "HQ Sector Reports (own sector)": "تقارير قطاع المقر الرئيسي (قطاعك الخاص)",
  "Focused TC dashboard — sector KPIs, sector project counts, pending technical approvals, sector risk summary.": "لوحة تحكم مركزة للمنسق التقني — مؤشرات أداء رئيسية للقطاع، أعداد مشاريع القطاع، الموافقات التقنية المعلقة، ملخص مخاطر القطاع.",
  "Technical review requests": "طلبات المراجعة التقنية",
  "Project transitions in assigned sector": "انتقالات مراحل المشاريع في القطاع الموكل",
  "Due dates for sector activities": "المواعيد النهائية لأنشطة القطاع",
  "Your sector assignment controls everything you can see. If data seems missing, verify your sector assignment with the System Administrator.": "تخصيص قطاعك يتحكم في كل ما يمكنك رؤيته. إذا بدت البيانات مفقودة، تحقق من تخصيص قطاعك مع مسؤول النظام.",
  "When a project spans multiple sectors, you will only see it if one of your sectors matches.": "عندما يمتد المشروع عبر قطاعات متعددة، لن تراه إلا إذا كان أحد قطاعاتك مطابقاً.",
  "A TC with a blank sector field is fail-closed — you will see nothing. Report this to your admin immediately.": "المنسق التقني الذي لديه حقل قطاع فارغ سيتم تقييد وصوله بالكامل — لن ترى شيئاً. أبلغ مسؤول النظام بذلك فوراً.",
  "Cannot see projects, reports, or plans outside assigned sector(s)": "لا يمكن رؤية المشاريع أو التقارير أو الخطط خارج القطاع (القطاعات) الموكل",
  "Cannot access user management": "لا يمكن الوصول إلى إدارة المستخدمين",
  "Cannot view budget data for other sectors": "لا يمكن عرض بيانات الميزانية للقطاعات الأخرى",
  "State Office Manager": "مدير مكتب الولاية",
  "State-level operations and staff management": "عمليات وإدارة موظفي الولاية",
  "State Office Managers oversee all CAFA operations within one assigned state. They manage state-level staff, create and edit state-level records, submit reports, and monitor the performance of their state's projects.": "يشرف مديرو مكاتب الولايات على جميع عمليات CAFA داخل ولاية واحدة موكلة إليهم. وهم يديرون موظفي الولاية، وينشئون ويعدلون سجلات الولاية، ويقدمون التقارير، ويراقبون أداء مشاريع ولايتهم.",
  "All projects in assigned state": "جميع المشاريع في الولاية الموكلة",
  "All reports for assigned state": "جميع التقارير للولاية الموكلة",
  "All plans for assigned state": "جميع الخطط للولاية الموكلة",
  "Risk register for assigned state": "سجل المخاطر للولاية الموكلة",
  "State-level dashboard": "لوحة تحكم على مستوى الولاية",
  "State programme officers reporting to them": "مسؤولو برامج الولاية الذين يتبعون لهم",
  "Projects (state-managed)": "المشاريع (تُدار من الولاية)",
  "Plans (monthly/quarterly)": "الخطط (شهرية/ربع سنوية)",
  "None — monitoring and oversight role; approval authority sits at HQ": "لا يوجد — دور مراقبة وإشراف؛ سلطة الموافقة تقع في المقر الرئيسي",
  "Project Reports for state projects": "تقارير المشاريع لمشاريع الولاية",
  "State dashboard — state KPIs, projects by locality, beneficiary breakdown for the state, pending submissions.": "لوحة تحكم الولاية — مؤشرات أداء الولاية، المشاريع حسب المنطقة، تفصيل المستفيدين للولاية، الطلبات المعلقة.",
  "State project transitions": "انتقالات مراحل مشاريع الولاية",
  "Risk escalations in assigned state": "تصعيد المخاطر في الولاية الموكلة",
  "Overdue plans and reports": "الخطط والتقارير المتأخرة",
  "Assignments to state staff": "المهام المسندة لموظفي الولاية",
  "Use the State Detail page (States module → your state) for a geographic breakdown of all activities.": "استخدم صفحة تفاصيل الولاية (وحدة الولايات ← ولايتك) للحصول على تفصيل جغرافي لجميع الأنشطة.",
  "Coordinate with Technical Coordinators for sector-specific reviews of state projects.": "نسّق مع المنسقين التقنيين لإجراء مراجعات خاصة بالقطاع لمشاريع الولاية.",
  "Monitor your state officers' submission progress from the Dashboard — overdue submissions appear in the Pending Approvals panel.": "راقب تقدم تقديمات مسؤولي ولايتك من لوحة التحكم — تظهر التقديمات المتأخرة في لوحة الموافقات المعلقة.",
  "State Programme Officer": "مسؤول البرنامج في الولاية",
  "Field operations — project and report creation": "عمليات ميدانية وإنشاء المشاريع والتقارير",
  "State Programme Officers are the primary data entry role in CAFA PMIS. They create project registrations, submit plans, log risks, and compile reports from field operations in their assigned state.": "مسؤولو برامج الولايات هم الدور الأساسي لإدخال البيانات في نظام CAFA PMIS. يقومون بإنشاء تسجيلات المشاريع، وتقديم الخطط، وتسجيل المخاطر، وتجميع التقارير من العمليات الميدانية في ولايتهم الموكلة.",
  "Projects they are assigned to": "المشاريع المسندة إليهم",
  "Reports they create": "التقارير التي ينشئونها",
  "Plans they create": "الخطط التي ينشئونها",
  "Risk register (create and update)": "سجل المخاطر (إنشاء وتحديث)",
  "System Manual (read-only)": "دليل النظام (للعرض فقط)",
  "File & Archive (upload and download)": "الملفات والأرشيف (رفع وتحميل)",
  "Plans (monthly/action/operational)": "الخطط (شهرية/إجرائية/تشغيلية)",
  "Comments on assigned entities": "التعليقات على الكيانات المسندة",
  "None — State Programme Officers submit; approval happens upstream": "لا يوجد — مسؤولو برامج الولايات يقدمون الطلبات؛ الموافقة تتم في مستويات أعلى",
  "Compact state officer dashboard — assigned projects, pending submissions, recent activities, risk status.": "لوحة تحكم مصغرة لمسؤول الولاية — المشاريع المسندة، الطلبات المعلقة، الأنشطة الأخيرة، حالة المخاطر.",
  "Approval decisions on your submissions": "قرارات الموافقة على تقديماتك",
  "Revision requests (Required Correction comments)": "طلبات المراجعة (تعليقات \"التصحيح المطلوب\")",
  "Save projects and reports as Draft before submitting — you can continue editing them later.": "احفظ المشاريع والتقارير كمسودة قبل التقديم — يمكنك متابعة تحريرها لاحقاً.",
  "Always upload at least one signed document before submitting a project.": "قم دائماً برفع وثيقة واحدة موقعة على الأقل قبل تقديم المشروع.",
  "Check the Comments tab regularly — reviewers may post Required Correction comments that need your attention before approval can proceed.": "تحقق من علامة تبويب التعليقات بانتظام — قد يقوم المراجعون بنشر تعليقات \"التصحيح المطلوب\" التي تتطلب اهتمامك قبل المضي قدماً في الموافقة.",
  "Project Officer": "مسؤول المشروع",
  "Project-specific data entry and reporting": "إدخال البيانات وإعداد التقارير الخاصة بالمشروع",
  "Project Officers support specific projects with data entry, activity tracking, and reporting. Their access is limited to the projects they are assigned to.": "يدعم مسؤولو المشاريع مشاريع محددة من خلال إدخال البيانات، وتتبع الأنشطة، وإعداد التقارير. وصولهم مقصور على المشاريع المسندة إليهم.",
  "Projects they are assigned to (read and limited edit)": "المشاريع المسندة إليهم (للقراءة وتعديل محدود)",
  "Reports for assigned projects": "تقارير المشاريع المسندة",
  "Risk register for assigned projects": "سجل المخاطر للمشاريع المسندة",
  "Activity logs and progress updates for assigned projects": "سجلات الأنشطة وتحديثات التقدم للمشاريع المسندة",
  "Document uploads for assigned projects": "رفع المستندات للمشاريع المسندة",
  "None — Project Officers do not have approval authority": "لا يوجد — مسؤولو المشاريع لا يملكون سلطة الموافقة",
  "Project Reports (assigned projects only)": "تقارير المشاريع (للمشاريع المسندة فقط)",
  "Basic dashboard — assigned project summaries and upcoming deadlines.": "لوحة تحكم أساسية — ملخصات المشاريع المسندة والمواعيد النهائية القادمة.",
  "Assignments and task updates": "المهام المسندة وتحديثات المهام",
  "Due date reminders for assigned work": "تذكيرات المواعيد النهائية للعمل المسند",
  "Keep activity progress updated regularly — your Programme Officer relies on this data for reports.": "حافظ على تحديث تقدم الأنشطة بانتظام — يعتمد مسؤول برنامجك على هذه البيانات للتقارير.",
  "Upload supporting documents for activities as they are completed.": "ارفع المستندات الداعمة للأنشطة فور إنجازها.",
  "If you need access to records you cannot see, ask your line manager to update your project assignment.": "إذا كنت بحاجة إلى الوصول إلى سجلات لا يمكنك رؤيتها، اطلب من مديرك المباشر تحديث إسناد المشروع الخاص بك.",
  "Cannot create projects, plans, or risks independently": "لا يمكن إنشاء مشاريع أو خطط أو مخاطر بشكل مستقل",
  "Cannot approve or reject any records": "لا يمكن اعتماد أو رفض أي سجلات",
  "Cannot access user management or audit log": "لا يمكن الوصول إلى إدارة المستخدمين أو سجل التدقيق",
  "Programme Assistant": "مساعد البرامج",
  "Administrative support and data entry": "دعم إداري وإدخال بيانات",
  "Programme Assistants support programme staff with data entry, document management, and administrative tasks. They have limited write access — primarily viewing assigned records and assisting with document uploads.": "يقوم مساعدو البرامج بدعم موظفي البرنامج في إدخال البيانات وإدارة المستندات والمهام الإدارية. لديهم صلاحية كتابة محدودة — تقتصر بشكل أساسي على عرض السجلات المسندة والمساعدة في رفع المستندات.",
  "Projects they are assigned to (read-only)": "المشاريع المسندة إليهم (للعرض فقط)",
  "Reports they are involved with (read-only)": "التقارير التي يشاركون فيها (للعرض فقط)",
  "Plans they are supporting (read-only)": "الخطط التي يدعمونها (للعرض فقط)",
  "Document uploads for assigned projects and reports": "رفع المستندات للمشاريع والتقارير المسندة",
  "None — Programme Assistants do not have approval authority": "لا يوجد — مساعدو البرامج لا يملكون سلطة الموافقة",
  "View assigned reports (read-only)": "عرض التقارير المسندة (للعرض فقط)",
  "Use File & Archive to upload and organise files as directed by your Programme Officer or Manager.": "استخدم \"الملفات والأرشيف\" لرفع وتنظيم الملفات حسب توجيهات مسؤول البرنامج أو المدير الخاص بك.",
  "Cannot create projects, reports, plans, or risks independently": "لا يمكن إنشاء مشاريع أو تقارير أو خطط أو مخاطر بشكل مستقل",
  "Cannot view records outside your assignments": "لا يمكن عرض سجلات خارج نطاق مهامك المسندة",
  "Viewer": "مستخدم للعرض",
  "Read-only access to assigned data": "عرض البيانات المصرح بها فقط",
  "Viewers have read-only access to specific programme data they have been granted access to. This role is typically used for donors, partners, or external stakeholders who need visibility without any edit access.": "يتمتع مستخدمو العرض بصلاحية القراءة فقط لبيانات برنامج محددة تم منحهم الوصول إليها. هذا الدور يُستخدم عادةً للمانحين أو الشركاء أو أصحاب المصلحة الخارجيين الذين يحتاجون إلى رؤية البيانات دون أي صلاحية تعديل.",
  "Projects explicitly shared with them (read-only)": "المشاريع التي تمت مشاركتها معهم صراحةً (للعرض فقط)",
  "Reports explicitly shared with them (read-only)": "التقارير التي تمت مشاركتها معهم صراحةً (للعرض فقط)",
  "View shared reports (read-only)": "عرض التقارير المشتركة (للعرض فقط)",
  "Limited dashboard — only data within their granted access scope.": "لوحة تحكم محدودة — فقط البيانات ضمن نطاق الوصول الممنوح لهم.",
  "Minimal — only explicit assignments": "بالحد الأدنى — فقط المهام المسندة صراحةً",
  "Contact your CAFA system administrator if you need access to additional records.": "اتصل بمسؤول نظام CAFA إذا كنت بحاجة إلى الوصول إلى سجلات إضافية.",
  "Use the System Manual to understand programme terminology and processes.": "استخدم دليل النظام لفهم مصطلحات وعمليات البرنامج.",
  "Cannot approve or reject anything": "لا يمكن اعتماد أو رفض أي شيء",
  "Cannot access user management, audit log, or financial data": "لا يمكن الوصول إلى إدارة المستخدمين أو سجل التدقيق أو البيانات المالية",
  "Data access is strictly limited to explicitly granted records": "الوصول إلى البيانات مقيد تماماً بالسجلات الممنوحة صراحةً"
};
